#!/bin/bash
# Copyright 2019 Ciena Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NAME=$1

P_ID=$(ps e -ww | grep _TAG=$NAME | grep -v grep | awk '{printf("%s %s\n", $1, $5)}' | grep -v bash | awk '{print $1}')

if [ -z "$P_ID" ]; then
    exit 1
else
    exec kill -9 $P_ID
fi

